// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deadlineinfo.proto

package deadlineinfo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	date "google.golang.org/genproto/googleapis/type/date"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Date                 *date.Date `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e44aeae6395c50e3, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetDate() *date.Date {
	if m != nil {
		return m.Date
	}
	return nil
}

type GetResponse struct {
	Date                 *date.Date `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e44aeae6395c50e3, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetDate() *date.Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "deadlineinfo.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "deadlineinfo.GetResponse")
}

func init() { proto.RegisterFile("deadlineinfo.proto", fileDescriptor_e44aeae6395c50e3) }

var fileDescriptor_e44aeae6395c50e3 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xb1, 0x0b, 0x82, 0x50,
	0x10, 0x87, 0x93, 0xa2, 0xe1, 0x74, 0xe9, 0x4d, 0xe6, 0x14, 0x52, 0xd1, 0xf4, 0x24, 0x75, 0x6c,
	0x0a, 0xc1, 0xa5, 0xc9, 0xb1, 0x4d, 0xf3, 0xd2, 0x07, 0xf6, 0xee, 0x95, 0xe7, 0xd0, 0x7f, 0x1f,
	0xe9, 0x90, 0x41, 0x43, 0xeb, 0x7d, 0x7c, 0xdc, 0xf7, 0x03, 0x51, 0x62, 0x5e, 0x36, 0x4a, 0xa3,
	0xd2, 0x57, 0x92, 0xe6, 0x41, 0x4c, 0xc2, 0x19, 0xdf, 0x3c, 0x28, 0x73, 0xc6, 0x81, 0xf8, 0x11,
	0x40, 0x8a, 0x9c, 0xe1, 0xbd, 0xc3, 0x96, 0xc5, 0x06, 0x66, 0x6f, 0xe6, 0x5a, 0x2b, 0x6b, 0x67,
	0x87, 0x0b, 0x59, 0x11, 0x55, 0x0d, 0x4a, 0x7e, 0x1a, 0x94, 0x49, 0xce, 0x98, 0xf5, 0xd8, 0x8f,
	0xc1, 0xee, 0xa5, 0xd6, 0x90, 0x6e, 0xf1, 0x4f, 0x2b, 0x3c, 0x81, 0x93, 0x8c, 0x32, 0xc4, 0x01,
	0xa6, 0x29, 0xb2, 0x70, 0xe5, 0x57, 0xf0, 0xa7, 0xc6, 0x5b, 0xfe, 0x20, 0xc3, 0x4b, 0x7f, 0x72,
	0xdc, 0x9e, 0xd7, 0x95, 0xe2, 0xba, 0x2b, 0xe4, 0x85, 0x6e, 0x41, 0xd3, 0x19, 0xa5, 0xb9, 0xc6,
	0x7d, 0xcc, 0x75, 0x30, 0xb6, 0x8a, 0x79, 0xbf, 0x33, 0x7a, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc8,
	0xc9, 0x4d, 0x34, 0x17, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeadlineinfoClient is the client API for Deadlineinfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeadlineinfoClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type deadlineinfoClient struct {
	cc *grpc.ClientConn
}

func NewDeadlineinfoClient(cc *grpc.ClientConn) DeadlineinfoClient {
	return &deadlineinfoClient{cc}
}

func (c *deadlineinfoClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/deadlineinfo.Deadlineinfo/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeadlineinfoServer is the server API for Deadlineinfo service.
type DeadlineinfoServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedDeadlineinfoServer can be embedded to have forward compatible implementations.
type UnimplementedDeadlineinfoServer struct {
}

func (*UnimplementedDeadlineinfoServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterDeadlineinfoServer(s *grpc.Server, srv DeadlineinfoServer) {
	s.RegisterService(&_Deadlineinfo_serviceDesc, srv)
}

func _Deadlineinfo_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeadlineinfoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deadlineinfo.Deadlineinfo/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeadlineinfoServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Deadlineinfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deadlineinfo.Deadlineinfo",
	HandlerType: (*DeadlineinfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Deadlineinfo_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deadlineinfo.proto",
}
